node { //node 
    def commit_id 
    //stage를 3개로 나눔 
    stage('Preparation'){
        checkout scm 
        sh "git rev-parse --short HEAD > .git/commit_id"

    }
    stage('test'){
        nodejs(nodeJsInstallationName: 'nodejs'){
            sh 'npm install --only=dev'
            sh 'npm test'
        }
    }
    stage('docker build/push'){
        docker.withRegistery('https://index.docker.io/v1/', 'dockerhub'){
            def app = docker.build('zzarbttoo/docker-nodejs-demo:${commit_id}, '.').push()
        }
    }


}