node {
   def commit_id
   stage('Preparation') {
     checkout scm
     bat "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'node_14') {
      dir('jenkins_test'){
       bat 'npm install'
       bat 'npm install --only=dev'
       bat 'npm test'
      }
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'docker_hub_id') {
       def app = docker.build("zzarbttoo/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}